/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: paxillop (https://sketchfab.com/paxillop)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/xbox-one-controller-free-97fb54c001f84a6896b6ce8eb7a1814d
title: Xbox One Controller Free
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { motion } from "framer-motion-3d";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
  };
  materials: {
    aiStandardSurface1SG: THREE.MeshStandardMaterial;
    aiStandardSurface11SG: THREE.MeshStandardMaterial;
    aiStandardSurface13SG: THREE.MeshStandardMaterial;
    aiStandardSurface14SG: THREE.MeshStandardMaterial;
    aiStandardSurface4SG: THREE.MeshStandardMaterial;
    aiStandardSurface6SG: THREE.MeshStandardMaterial;
  };
};

const appear = {
  initial: {
    opacity: 0,
    y: -20,
  },
  animate: {
    opacity: 1,
    y: 0,
    transition: {
      ease: [0.77, 0, 0.175, 1],
      duration: 1,
    },
  },
  exit: {
    opacity: 0,
    y: 100,
    transition: { ease: [0.77, 0, 0.175, 1], duration: 0.8 },
  },
};

export default function Controller(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/controller.glb") as GLTFResult;
  return (
    <motion.group variants={appear} initial="initial" animate="animate">
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_2.geometry}
            material={materials.aiStandardSurface1SG}
          />
          <mesh
            geometry={nodes.Object_3.geometry}
            material={materials.aiStandardSurface11SG}
          />
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials.aiStandardSurface11SG}
          />
          <mesh
            geometry={nodes.Object_5.geometry}
            material={materials.aiStandardSurface13SG}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials.aiStandardSurface13SG}
          />
          <mesh
            geometry={nodes.Object_7.geometry}
            material={materials.aiStandardSurface14SG}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials.aiStandardSurface4SG}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials.aiStandardSurface4SG}
          />
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials.aiStandardSurface4SG}
          />
          <mesh
            geometry={nodes.Object_11.geometry}
            material={materials.aiStandardSurface6SG}
          />
        </group>
      </group>
    </motion.group>
  );
}

useGLTF.preload("/controller.glb");
