/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: paxillop (https://sketchfab.com/paxillop)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/xbox-one-controller-free-97fb54c001f84a6896b6ce8eb7a1814d
title: Xbox One Controller Free
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useSpring, animated } from "@react-spring/three";

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh;
    Object_3: THREE.Mesh;
    Object_4: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_11: THREE.Mesh;
  };
  materials: {
    aiStandardSurface1SG: THREE.MeshStandardMaterial;
    aiStandardSurface11SG: THREE.MeshStandardMaterial;
    aiStandardSurface13SG: THREE.MeshStandardMaterial;
    aiStandardSurface14SG: THREE.MeshStandardMaterial;
    aiStandardSurface4SG: THREE.MeshStandardMaterial;
    aiStandardSurface6SG: THREE.MeshStandardMaterial;
  };
};

export default function Controller(props: React.ComponentProps<"group">) {
  const { nodes, materials } = useGLTF("/controller.glb") as unknown as GLTFResult;
  
  const springs = useSpring({
    from: { 
      scale: 0, 
      opacity: 0,
      positionY: -2
    },
    to: { 
      scale: 1, 
      opacity: 1,
      positionY: 0
    },
    config: { 
      tension: 280, 
      friction: 60
    }
  });

  return (
    <animated.group 
      scale={springs.scale}
      position-y={springs.positionY}
    >
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <animated.mesh
            geometry={nodes.Object_2.geometry}
            material={materials.aiStandardSurface1SG}
            material-opacity={springs.opacity}
          />
          <animated.mesh
            geometry={nodes.Object_3.geometry}
            material={materials.aiStandardSurface11SG}
            material-opacity={springs.opacity}
          />
          <animated.mesh
            geometry={nodes.Object_4.geometry}
            material={materials.aiStandardSurface11SG}
            material-opacity={springs.opacity}
          />
          <animated.mesh
            geometry={nodes.Object_5.geometry}
            material={materials.aiStandardSurface13SG}
            material-opacity={springs.opacity}
          />
          <animated.mesh
            geometry={nodes.Object_6.geometry}
            material={materials.aiStandardSurface13SG}
            material-opacity={springs.opacity}
          />
          <animated.mesh
            geometry={nodes.Object_7.geometry}
            material={materials.aiStandardSurface14SG}
            material-opacity={springs.opacity}
          />
          <animated.mesh
            geometry={nodes.Object_8.geometry}
            material={materials.aiStandardSurface4SG}
            material-opacity={springs.opacity}
          />
          <animated.mesh
            geometry={nodes.Object_9.geometry}
            material={materials.aiStandardSurface4SG}
            material-opacity={springs.opacity}
          />
          <animated.mesh
            geometry={nodes.Object_10.geometry}
            material={materials.aiStandardSurface4SG}
            material-opacity={springs.opacity}
          />
          <animated.mesh
            geometry={nodes.Object_11.geometry}
            material={materials.aiStandardSurface6SG}
            material-opacity={springs.opacity}
          />
        </group>
      </group>
    </animated.group>
  );
}

useGLTF.preload("/controller.glb");