/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tejay21 (https://sketchfab.com/tejay21)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ath-m50x-headphone-ada0fcae10a1403c8c5bae1745a738f0
title: ATH-M50X Headphone
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useSpring, animated } from "@react-spring/three";

type GLTFResult = GLTF & {
  nodes: {
    ["8_EarCab001_earCab_0"]: THREE.Mesh;
    ["8_EarCab001_earCabFabric_0"]: THREE.Mesh;
    ["7_EarCover001_Headphone_Default_0"]: THREE.Mesh;
    ["7_EarCover001_MetalRing_0"]: THREE.Mesh;
    ["6_EarCoverHole001_Headphone_Default_0"]: THREE.Mesh;
    ["4_EarCoverConnector001__0"]: THREE.Mesh;
    ["5_EarCoverConnectorHolder001_Headphone_Default_0"]: THREE.Mesh;
    ["2_X_Connector_Bottom001_Headphone_Default_0"]: THREE.Mesh;
    ["2_X_Connector_Bottom001_MetalRing_0"]: THREE.Mesh;
    ["3_Logo001_Headphone_Default_0"]: THREE.Mesh;
    ["2_X_Connector_Top001_Headphone_Default_0"]: THREE.Mesh;
    ["01_MetalBar001_HeadbarMetalclean_0"]: THREE.Mesh;
    ["01_MetalBar001_HeadbarMetal_0"]: THREE.Mesh;
    ["01_MetalBar001_Headphone_Default_0"]: THREE.Mesh;
    ["02_FabricBar001_earCab_0"]: THREE.Mesh;
    ["02_BarEnd001_Headphone_Default_0"]: THREE.Mesh;
    ["02_Screws003_Screw_0"]: THREE.Mesh;
    ["02_Screws004_Screw_0"]: THREE.Mesh;
    ["02_Screws005_Screw_0"]: THREE.Mesh;
  };
  materials: {
    earCab: THREE.MeshStandardMaterial;
    earCabFabric: THREE.MeshStandardMaterial;
    Headphone_Default: THREE.MeshStandardMaterial;
    MetalRing: THREE.MeshStandardMaterial;
    ["4_EarCoverConnector.001__0"]: THREE.MeshStandardMaterial;
    ["HeadbarMetal.clean"]: THREE.MeshStandardMaterial;
    HeadbarMetal: THREE.MeshStandardMaterial;
    Screw: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: React.ComponentProps<"group">) {
  const { nodes, materials } = useGLTF("/headphone.glb") as unknown as GLTFResult;
  

  const springs = useSpring({
    from: { 
      scale: 0, 
      opacity: 0,
      positionY: -2
    },
    to: { 
      scale: 1, 
      opacity: 1,
      positionY: 0
    },
    config: { 
      tension: 280, 
      friction: 60
    }
  });

  return (
    <animated.group 
      scale={springs.scale}
      position-y={springs.positionY}
    >
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <group
              position={[2.14, 6.3, 4.68]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={100}
            >
              <group
                position={[-0.06, 0.05, -0.01]}
                rotation={[-3.09, -1.52, 1.84]}
              >
                <animated.mesh
                  geometry={nodes["8_EarCab001_earCab_0"].geometry}
                  material={materials.earCab}
                  material-opacity={springs.opacity}
                />
                <animated.mesh
                  geometry={nodes["8_EarCab001_earCabFabric_0"].geometry}
                  material={materials.earCabFabric}
                  material-opacity={springs.opacity}
                />
              </group>
              <group
                position={[-0.08, 0.04, 0.01]}
                rotation={[-3.09, -1.52, 1.84]}
              >
                <animated.mesh
                  geometry={nodes["7_EarCover001_Headphone_Default_0"].geometry}
                  material={materials.Headphone_Default}
                  material-opacity={springs.opacity}
                />
                <animated.mesh
                  geometry={nodes["7_EarCover001_MetalRing_0"].geometry}
                  material={materials.MetalRing}
                  material-opacity={springs.opacity}
                />
              </group>
              <group
                position={[-0.07, 0.08, -0.01]}
                rotation={[-Math.PI, -1.52, 1.57]}
                scale={1.29}
              >
                <animated.mesh
                  geometry={
                    nodes["6_EarCoverHole001_Headphone_Default_0"].geometry
                  }
                  material={materials.Headphone_Default}
                  material-opacity={springs.opacity}
                />
              </group>
              <group
                position={[-0.09, 0.05, 0.01]}
                rotation={[0, -0.48, -Math.PI / 2]}
                scale={[1, 0.75, 1]}
              >
                <animated.mesh
                  geometry={nodes["4_EarCoverConnector001__0"].geometry}
                  material={materials["4_EarCoverConnector.001__0"]}
                  material-opacity={springs.opacity}
                />
              </group>
              <group
                position={[-0.08, 0.03, -0.01]}
                rotation={[Math.PI / 2, 0, -1.09]}
              >
                <animated.mesh
                  geometry={
                    nodes["5_EarCoverConnectorHolder001_Headphone_Default_0"]
                      .geometry
                  }
                  material={materials.Headphone_Default}
                  material-opacity={springs.opacity}
                />
              </group>
              <group
                position={[-0.1, 0.05, 0.04]}
                rotation={[Math.PI / 2, 0, -1.35]}
              >
                <animated.mesh
                  geometry={
                    nodes["2_X_Connector_Bottom001_Headphone_Default_0"]
                      .geometry
                  }
                  material={materials.Headphone_Default}
                  material-opacity={springs.opacity}
                />
                <animated.mesh
                  geometry={
                    nodes["2_X_Connector_Bottom001_MetalRing_0"].geometry
                  }
                  material={materials.MetalRing}
                  material-opacity={springs.opacity}
                />
              </group>
              <group
                position={[-0.09, 0.05, 0.02]}
                rotation={[0, -0.38, -Math.PI / 2]}
              >
                <animated.mesh
                  geometry={nodes["3_Logo001_Headphone_Default_0"].geometry}
                  material={materials.Headphone_Default}
                  material-opacity={springs.opacity}
                />
              </group>
              <group
                position={[-0.1, 0.05, 0.05]}
                rotation={[0, -0.22, -Math.PI / 2]}
              >
                <animated.mesh
                  geometry={
                    nodes["2_X_Connector_Top001_Headphone_Default_0"].geometry
                  }
                  material={materials.Headphone_Default}
                  material-opacity={springs.opacity}
                />
              </group>
              <group position={[-0.02, 0.05, 0.08]}>
                <animated.mesh
                  geometry={
                    nodes["01_MetalBar001_HeadbarMetalclean_0"].geometry
                  }
                  material={materials["HeadbarMetal.clean"]}
                  material-opacity={springs.opacity}
                />
                <animated.mesh
                  geometry={nodes["01_MetalBar001_HeadbarMetal_0"].geometry}
                  material={materials.HeadbarMetal}
                  material-opacity={springs.opacity}
                />
                <animated.mesh
                  geometry={
                    nodes["01_MetalBar001_Headphone_Default_0"].geometry
                  }
                  material={materials.Headphone_Default}
                  material-opacity={springs.opacity}
                />
              </group>
              <group position={[-0.02, 0.05, 0.08]} scale={[1, 1.87, 1]}>
                <animated.mesh
                  geometry={nodes["02_FabricBar001_earCab_0"].geometry}
                  material={materials.earCab}
                  material-opacity={springs.opacity}
                />
              </group>
              <group position={[-0.1, 0.05, 0.11]} rotation={[0, 0.35, 0]}>
                <animated.mesh
                  geometry={nodes["02_BarEnd001_Headphone_Default_0"].geometry}
                  material={materials.Headphone_Default}
                  material-opacity={springs.opacity}
                />
              </group>
              <group
                position={[-0.1, 0.04, 0.11]}
                rotation={[3.13, 1.21, -1.56]}
              >
                <animated.mesh
                  geometry={nodes["02_Screws003_Screw_0"].geometry}
                  material={materials.Screw}
                  material-opacity={springs.opacity}
                />
              </group>
              <group
                position={[-0.1, 0.06, 0.11]}
                rotation={[3.13, 1.21, -1.56]}
              >
                <animated.mesh
                  geometry={nodes["02_Screws004_Screw_0"].geometry}
                  material={materials.Screw}
                  material-opacity={springs.opacity}
                />
              </group>
              <group
                position={[-0.1, 0.03, 0.06]}
                rotation={[0.18, 1.56, 1.39]}
                scale={0.59}
              >
                <animated.mesh
                  geometry={nodes["02_Screws005_Screw_0"].geometry}
                  material={materials.Screw}
                  material-opacity={springs.opacity}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </animated.group>
  );
}

useGLTF.preload("/headphone.glb");